package tech.pcreate.easyroom.Entity;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Index;
import android.arch.persistence.room.PrimaryKey;
import android.arch.persistence.room.TypeConverters;
import android.support.annotation.NonNull;

import java.io.Serializable;
import java.util.Date;

import tech.pcreate.easyroom.Utilities.TimeStampConverter;

@Entity(tableName = "my_table")
public class MyEntity  implements Serializable {

    /** Columns already available are:
     * 1. id (autogenerated integer)
     * 2. title (String)
     * 3. content (String)
     * 4. time (Date, with TimeConverter class in Utilities)
     */

    @NonNull
    @ColumnInfo(name = "id")
    @PrimaryKey(autoGenerate = true)
    private int id;

    @ColumnInfo(name = "title")
    private String title;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @ColumnInfo(name = "content")
    private String content;

    @NonNull
    @ColumnInfo(name = "time")
    @TypeConverters({TimeStampConverter.class})
    private Date wroteAt;


    public MyEntity(int id,  String content, @NonNull Date wroteAt, String title) {
        this.id = id;
        this.content = content;
        this.wroteAt = wroteAt;
        this.title = title;
    }

    public MyEntity() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }


    public String getContent() {
        return content;
    }

    public void setContent(@NonNull String content) {
        this.content = content;
    }

    @NonNull
    public Date getWroteAt() {
        return wroteAt;
    }

    public void setWroteAt(@NonNull Date wroteAt) {
        this.wroteAt = wroteAt;
    }
}

